spring:
  profiles:
    active: development
  application:
    name: friend-service
  cloud:
    stream:
      bindings:
        output:
          destination: friend
          contentType: 'application/json'
      kafka:
        binder:
          brokers: localhost:9092
#          zkNodes: localhost
#          defaultZkPort: 2181
#          defaultBrokerPort: 9092 
      binders:
        kafka:
          default-candidate: true            
server:
  port: 8082
---
spring:
  profiles: development
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          defaultBrokerPort: 29092
          zkNodes: zookeeper
          defaultZkPort: 32181
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
eureka:
  client:
    enabled: false